# RocketMQ Broker 配置（演示部署，独立 Broker 容器）
brokerClusterName=DefaultCluster
brokerName=broker-a
brokerId=0
brokerIP1=rocketmq-broker
listenPort=10911
namesrvAddr=rocketmq-namesrv:9876
storePathRootDir=/home/rocketmq/store
deleteWhen=04
fileReservedTime=48
autoCreateTopicEnable=true
sendMessageThreadPoolNums=64
pullMessageThreadPoolNums=64
storePutMessageThreadPoolNums=32
dispatchMessageThreadPoolNums=32
