# RocketMQ production master broker configuration.
brokerClusterName=DefaultCluster
brokerName=broker-a
brokerId=0
brokerRole=SYNC_MASTER
flushDiskType=SYNC_FLUSH
brokerIP1=rocketmq-broker-master
listenPort=10911
haListenPort=10912
namesrvAddr=rocketmq-namesrv-1:9876;rocketmq-namesrv-2:9876
storePathRootDir=/home/rocketmq/store
deleteWhen=04
fileReservedTime=48
autoCreateTopicEnable=true
sendMessageThreadPoolNums=64
pullMessageThreadPoolNums=64
storePutMessageThreadPoolNums=32
dispatchMessageThreadPoolNums=32
